### ISSUE TITLE
Can SCJS be used on a home PC or only on a remote server?

### ISSUE THREAD

**Issue by liruhan** [walterhiggins/ScriptCraft#454]
i just want to run in personal game

**Comment by MrDoomBringer** [comment]
Nope! However, you can have a server be totally personal and only accessible to you if you don't port forward. For more information: https://minecraft.gamepedia.com/Tutorials/Setting_up_a_server

**Comment by TonyGravagno** [comment]
A few years ago I was working on new docs, which unfortunately I never got back into the core here. The docs are still valid however, and include a lot of detail that is not in the docs here - including all info about installing and running a local SMP (multi-player) server.

[Get the docs here](https://github.com/TonyGravagno/ScriptCraft/blob/bad-zombie/docs/docs.md). The README.md in that project also includes links to other help resources for questions like this. And there is a [Discord server. (This link expires](https://discord.gg/aQqQaNc7c6), I'll post another one somewhere later unless Walter posts a permanent link.

DO NOT USE THE CODE IN MY REPO! It is old and behind this "master" version. It will not work with any Minecraft release published since 2017. One of these days I might get back to the code and/or the docs but for now just use the docs as-is.

Fixing the title of this ticket and then closing as Resolved.

**Comment by tiredoftry** [comment]
Thank you for the additional documentation Tony.  I used a local server for my tech talks to 3rd - 5th graders at the school where my wife teaches.  Quick/easy to get setup and great way to get started with ScriptCraft.
